version: '3'

services:
  bitcoders-react:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: vladimirovsk/bitcoders-react:master
    container_name: bitcoders-react
    restart: always
    ports:
      - '3000:3000'
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  staticbuild: