version: '3'

services:
  itcoder-react:
    build:
      context: .
      dockerfile: Dockerfile
#    image: vladimirovsk/itcoder-react:master
    container_name: itcoder-react
    restart: always
    ports:
      - '3000:3000'
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  staticbuild:
