name: Bitcoders Front

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: docker build . -t vladimirovsk/bitcoders-react:master
      - name: publish
        run: | 
          docker login -u vladimirovsk -p ${{ secrets.DOCKER_PASSWORD }}
          docker push vladimirovsk/bitcoders-react:master